# Generated by Django 5.2.10 on 2026-01-12 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this tenant (e.g., 'Contoso Production')",
                        max_length=255,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        help_text="Azure AD Tenant ID (GUID)", max_length=36
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="Azure AD Application (Client) ID", max_length=36
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("secret", "Client Secret"),
                        ],
                        default="certificate",
                        help_text="Authentication method for this tenant",
                        max_length=20,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client secret (only for secret auth method)",
                        max_length=255,
                    ),
                ),
                (
                    "certificate_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to certificate file (.pfx or .pem)",
                        max_length=500,
                    ),
                ),
                (
                    "certificate_thumbprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Certificate thumbprint (for PowerShell)",
                        max_length=64,
                    ),
                ),
                (
                    "certificate_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Certificate password (if protected)",
                        max_length=255,
                    ),
                ),
                (
                    "api_method",
                    models.CharField(
                        choices=[
                            ("graph", "Microsoft Graph API"),
                            ("powershell", "Exchange Online PowerShell"),
                        ],
                        default="graph",
                        help_text="API method for retrieving message traces",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Exchange organization name (e.g., contoso.onmicrosoft.com)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this tenant is active for trace collection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this tenant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who granted this permission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Permission",
                "verbose_name_plural": "Tenant Permissions",
                "ordering": ["user__username", "tenant__name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrator"), ("user", "User")],
                        default="user",
                        help_text="User role determines access level",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                fields=("tenant_id",), name="unique_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantpermission",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant"), name="unique_user_tenant_permission"
            ),
        ),
    ]
