# Generated by Django 5.2.12 on 2026-03-23 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_app_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        help_text="Tenant name at the time of the action (preserved after deletion)",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Tenant Created"),
                            ("update", "Tenant Updated"),
                            ("delete", "Tenant Deleted"),
                            ("test_connection", "Connection Test"),
                            ("certificate_upload", "Certificate Upload"),
                        ],
                        help_text="The type of action performed",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        help_text="Whether the action succeeded or failed",
                        max_length=10,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable summary of what happened",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full error message if the action failed",
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python traceback for debugging failed operations",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data about the action (e.g., changed fields)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The tenant this action was performed on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Audit Log",
                "verbose_name_plural": "Tenant Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
