# Generated by Django 5.2.12 on 2026-03-25 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_switch_powershell_to_graph"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsettings",
            name="scheduled_pull_hour",
        ),
        migrations.RemoveField(
            model_name="appsettings",
            name="scheduled_pull_minute",
        ),
        migrations.AddField(
            model_name="appsettings",
            name="scheduled_pull_interval_hours",
            field=models.IntegerField(
                default=24,
                help_text="Hours component of the pull interval (0-168)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(168),
                ],
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="scheduled_pull_interval_minutes",
            field=models.IntegerField(
                default=0,
                help_text="Minutes component of the pull interval (0-59)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
    ]
