# Generated by Django 5.2.12 on 2026-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_change_scheduled_pull_to_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="initial_pull_done",
            field=models.BooleanField(
                default=False,
                help_text="Whether the initial full historical data pull (10 days) has been completed",
            ),
        ),
    ]
