# Generated by Django 5.2.10 on 2026-01-12 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PullHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the pull operation started",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the pull operation completed",
                        null=True,
                    ),
                ),
                (
                    "pull_start_date",
                    models.DateTimeField(
                        help_text="Start of the date range being pulled"
                    ),
                ),
                (
                    "pull_end_date",
                    models.DateTimeField(
                        help_text="End of the date range being pulled"
                    ),
                ),
                (
                    "records_pulled",
                    models.IntegerField(
                        default=0, help_text="Total number of records retrieved"
                    ),
                ),
                (
                    "records_new",
                    models.IntegerField(
                        default=0,
                        help_text="Number of new records (not previously in database)",
                    ),
                ),
                (
                    "records_updated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of existing records that were updated",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Running", "Running"),
                            ("Success", "Success"),
                            ("Partial", "Partial Success"),
                            ("Failed", "Failed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Running",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if the pull failed",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("Scheduled", "Scheduled"), ("Manual", "Manual")],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Username or 'system' for scheduled pulls",
                        max_length=150,
                    ),
                ),
                (
                    "api_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API method used (graph, powershell, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The MS365 tenant this pull was for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_history",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull History",
                "verbose_name_plural": "Pull History",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="MessageTraceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="Internet Message ID from the email header (RFC 5322)",
                        max_length=512,
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the message was received by Exchange Online",
                    ),
                ),
                (
                    "sender",
                    models.EmailField(
                        db_index=True, help_text="Sender email address", max_length=320
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(
                        db_index=True,
                        help_text="Recipient email address",
                        max_length=320,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Email subject line",
                        max_length=1000,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                            ("Pending", "Pending"),
                            ("Expanded", "Expanded"),
                            ("Quarantined", "Quarantined"),
                            ("FilteredAsSpam", "Filtered as Spam"),
                            ("None", "None"),
                            ("Unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="Unknown",
                        help_text="Delivery status of the message",
                        max_length=50,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("Inbound", "Inbound"),
                            ("Outbound", "Outbound"),
                            ("Internal", "Internal"),
                            ("Unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="Unknown",
                        help_text="Message direction (Inbound/Outbound/Internal)",
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        default=0, help_text="Message size in bytes"
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured event details and metadata",
                    ),
                ),
                (
                    "trace_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this record was pulled from Exchange Online",
                    ),
                ),
                (
                    "raw_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete raw API response for this message",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The MS365 tenant this trace belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_traces",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Trace Log",
                "verbose_name_plural": "Message Trace Logs",
                "ordering": ["-received_date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "received_date"],
                        name="traces_mess_tenant__548d94_idx",
                    ),
                    models.Index(
                        fields=["received_date", "sender"],
                        name="traces_mess_receive_c17176_idx",
                    ),
                    models.Index(
                        fields=["received_date", "recipient"],
                        name="traces_mess_receive_d4ba70_idx",
                    ),
                    models.Index(
                        fields=["status", "direction"],
                        name="traces_mess_status_ec2456_idx",
                    ),
                    models.Index(
                        fields=["trace_date"], name="traces_mess_trace_d_cba3eb_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "message_id", "recipient", "received_date"),
                        name="unique_tenant_message_recipient_date",
                    )
                ],
            },
        ),
    ]
